name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for creating an issue! All feedback and suggestions are welcome. Most issues are reviewed and responded to during weekends, so expect an update then. :)'
        pr-message: 'Achievement unlocked! Thanks for creating your first PR, super excited to work with you on this.'
